[project]
name = "payments_service"
version = "0.1.0"
description = "A service for managing payments, invoices, and payouts."
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
