name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    name: Lint and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linting Tools
        run: pip install ruff

      - name: Lint backend (Python)
        run: ruff check ./apps/backend/services

      - name: Install All Service Dependencies
        run: |
          for d in ./apps/backend/services/*/; do
            if [ -f "$d/requirements.txt" ]; then
              pip install -r "$d/requirements.txt";
            fi
          done

      - name: Install All Services in Editable Mode
        run: |
          pip install \
            -e ./apps/backend/services/admin \
            -e ./apps/backend/services/auth \
            -e ./apps/backend/services/catalog \
            -e ./apps/backend/services/chat \
            -e ./apps/backend/services/orders \
            -e ./apps/backend/services/orgs \
            -e ./apps/backend/services/payments \
            -e ./apps/backend/services/rfq \
            -e ./apps/backend/services/search

      - name: Install Test Dependencies
        run: pip install pytest httpx python-jose

      - name: Run Backend Tests
        run: pytest ./apps/backend/services/

  build-and-push-images:
    name: Build and Push Docker Images
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' # Only run on merge to main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [admin, auth, catalog, chat, orders, orgs, payments, rfq, search]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend/services/${{ matrix.service }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/marketplace-${{ matrix.service }}:latest

  # Frontend jobs can remain as they are for now
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/frontend/web/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./apps/frontend/web
        run: npm ci

      - name: Lint frontend (TypeScript)
        working-directory: ./apps/frontend/web
        run: npm run lint
